### ISSUE TITLE
ERROR: Couldn't initialise service "wdio-native-app-compare".

### ISSUE THREAD

**Issue by LayMuiToh** [wswebcreation/wdio-native-app-compare#10]
**Environment (please complete the following information):**
 - Node.js version: 11.13.0
 - NPM version: 6.7.0
 - webdriver.io version: 4.14.1
 - wdio-native-app-compare version: 0.7.0

**Config of webdriver.io and the plugin**
 plugins: {
        'wdio-screenshot': {},
        'wdio-native-app-compare': {
            baselineFolder: '.dist/image-compare/baseline',
            screenshotPath: '.dist/image-compare/screenshots',
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutIphoneXBottomBar: true,
            blockOutNavigationBar: true,
            debug: true,

            // See Options for more options
            //..
          },
    },
**Describe the bug**

**To Reproduce**
ERROR: Couldn't initialise service "wdio-native-app-compare".
Error: The module '/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:846:18)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:805:30)

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wswebcreation** [comment]
The 0.7.0 version can't work with Node 11, if you revert to 10 it will work.
0.7.0 will not be maintained anymore, going to close it now
