### ISSUE TITLE
Local Native app comparison is working as expected but failing on SauceLabs using the same code

### ISSUE THREAD

**Issue by semeguze** [wswebcreation/wdio-native-app-compare#34]
------------
🚀 **_Describe your question with as much detail as possible_**

Currently I'm playing around with this service on WDIO and performance wise it's pretty nice, thank you guys! 
On local executions it is working as expected ✅, the comparison is completed and the diff image is included into the diff folder.

```javascript
[0-0] 2022-07-30T00:02:52.311Z INFO webdriver: COMMAND getWindowRect()
[0-0] 2022-07-30T00:02:52.311Z INFO webdriver: [GET] http://localhost:4723/session/f39dafd8-e7b9-4c9a-bf4c-1758d537ed90/window/rect
[0-0] 2022-07-30T00:02:52.388Z INFO webdriver: RESULT { width: 1080, height: 2040, x: 0, y: 0 }
[0-0] 2022-07-30T00:02:53.206Z INFO webdriver: RESULT {
[0-0]   fileName: 'android_2-android_emulator.png',
[0-0]   folders: {
[0-0]     actual: '/Users/sebas/.../test-automation/.tmp/image-compare/actual',
[0-0]     baseline: '/Users/sebas/.../test-automation/test/image-baseline',
[0-0]     diff: '/Users/sebas/.../test-automation/.tmp/image-compare/diff'
[0-0]   },
[0-0]   misMatchPercentage: 66.59
[0-0] }
```

However, when I'm running the exact same test on **SauceLabs** i'm getting the following error message:
```javascript
TypeError: browser.compareScreen is not a function
    at TutorialPage.dismissTutorial (/Users/sebastian/.../tutorial.page.js:31:25)
    at async World.<anonymous> (/Users/sebastian/.../src/step-definitions/MOO.js:33:3)
```
------------
🚀 **_If it's about a specific piece of code, try and include some of it to support your question._**

This is the current configuration for my `exports.config` file:
```javascript
  services: [
    [
      'appium',
      {
        args: {
          port: 4723
        }
      }
    ],
    [
      'native-app-compare',
      {
          baselineFolder: './test/image-baseline',
          screenshotPath: '.tmp/image-compare',
          blockOutStatusBar: true
      },
    ]
  ]
```

My sauce capabilities:
```javascript
  capabilities: [
    {
      platformName: 'Android',
      'appium:appPackage': '...',
      'appium:appActivity': 'com.....SplashActivity',
      'appium:automationName': 'uiautomator2',
      'appium:deviceName': 'Google Pixel 3 XL GoogleAPI Emulator',
      'appium:platformVersion': '12.0',
      'appium:orientation': 'PORTRAIT',
      'appium:app': sharedConfig.androidApk,
      'sauce:options': {
        tunnelIdentifier: sharedConfig.tunnelIdentifier
      }
    }
  ]
```

My `package.json` file:
```javascript
{
    "name": "webdriverio-tests",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "@wdio/allure-reporter": "^7.20.0",
        "@wdio/appium-service": "^7.17.3",
        "@wdio/cli": "^7.19.6",
        "@wdio/cucumber-framework": "^7.20.3",
        "@wdio/devtools-service": "^7.19.1",
        "@wdio/local-runner": "^7.19.5",
        "@wdio/sauce-service": "^7.19.7",
        "@wdio/spec-reporter": "^7.19.5",
        "chromedriver": "^100.0.0",
        "eslint": "^8.16.0",
        "eslint-config-standard": "^16.0.3",
        "eslint-plugin-import": "^2.25.4",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-promise": "^5.2.0",
        "wdio-native-app-compare-service": "^2.0.0",
        "wdio-selenium-standalone-service": "0.0.12",
        "wdio-wait-for": "^2.2.1"
    },
    "scripts": {
       ...
    },
    "dependencies": {
        "@cucumber/cucumber": "^8.3.0",
        "appium": "^1.22.3",
        "chai": "^4.3.6",
        "dateformat": "^3.0.3",
        "deepmerge": "^4.2.2",
        "eslint-plugin-wdio": "^7.19.4",
        "gherkin-lint": "^4.2.2",
        "jsdoc": "^3.6.10",
        "jsonpath": "^1.1.1",
        "lodash": "^4.17.21",
        "request": "^2.88.2",
        "request-promise": "^4.2.6",
        "wdio-chromedriver-service": "^7.3.2",
        "webdriverio": "^7.19.5",
        "xml2js": "^0.4.23"
    }
}
```

And the way I'm using the service:
```javascript
    let matchPercentage = (
      await browser.compareScreen('android_2', {
        //.. options here
      })
    ).misMatchPercentage;
```

------------
🚀 **Environment (please complete the following information):**

-   Node.js version: v14.20.0
-   NPM version: 6.14.17
-   webdriver.io version: 7.19.5
-   wdio-native-app-compare version: 2.0.0

------------
🚀 **Additional context**

I would like to know if there is a restriction for running this on SauceLabs or if it just me missing something!
Thanks for any help!!

**Comment by wswebcreation** [comment]
Hi @semeguze 

thanks for the feedback, really appreciate it

Regarding running on Sauce Labs, there is no restriction, I’m almost 100% sure it’s in you config

can you share you complete config? The one also with Sauce in it? You didn’t post that here

tnx

**Comment by semeguze** [comment]
Thank you for you quick response, really appreciate it too! 😃 

Well, it looks like you were totally right, in my custom config file for sauce I was missing the `'native-app-compare'` under services declaration hahha 😵‍💫 

Declaring my `wdio.sauce.conf.js` file like this is now working as expected with the following config:
```javascript
exports.config = {
  isSaucelabs: true,
  region: 'us',

  // =================
  // Sauce Credentials
  // =================
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  tunnelIdentifier: process.env.SAUCE_POOL_TUNNEL_ID,

  // =================
  // Apps
  // =================
  androidApk: 'storage:filename=x.apk',
  iosSimulator: 'storage:filename=y.zip',
  iosRealDevice: 'storage:filename=z.ipa',

  // ========
  // Services
  // ========
  services: [
    [
      'sauce'
      // If you want to use you own tunnel, uncomment this block of code, and
      // use the same 'tunnelIdentifier' name at the top in the 'Sauce Credentials' section.
      // ,{
      //   region: 'us',
      //   sauceConnect: true,
      //   sauceConnectOpts: {
      //     verbose: true,
      //     tunnelIdentifier: 'your-own-tunnel-name'
      //   }
      // }
    ],
    [
      'native-app-compare',
      {
          baselineFolder: './img/visual.validation/commons',
          screenshotPath: './img/visual.validation/temp.comparisons',
          blockOutStatusBar: true,
          imageNameFormat: `{tag}-{platformName}`
      },
    ]
  ]
};

```

Based on this I think this is already resolved hahaha, thank you so much for your help 👍 🚀

**Comment by semeguze** [comment]
One last question haha

On SL the Virtual Device manages a different resolution, is there an option that could I use to resize the Sauce screenshot to match the baseline image?
I saw the resizeDimensions option but it looks like it requires specific values per axis

Thanks!

**Comment by wswebcreation** [comment]
Here’s an example I use for testing this module

https://github.com/wswebcreation/wdio-image-comparison-service/blob/main/tests/configs/wdio.shared.conf.js#L53

will close it for now

**Comment by wswebcreation** [comment]
By the way, if you look in my sample config folder you can also see you can extend the configs and concatenate the services
