### ISSUE TITLE
can't do npm install wdio-native-app-compare

### ISSUE THREAD

**Issue by LayMuiToh** [wswebcreation/wdio-native-app-compare#7]
**Environment (please complete the following information):**
 - Node.js version: 9.1.0
 - NPM version: 6.4.1
 - webdriver.io version: 4.14.1
 - wdio-native-app-compare version: NA (not able to install

**Config of webdriver.io and the plugin**
An example of how you configured the plugin in your webdriver.io config

**Describe the bug**
npm install wdio-native-app-compare --save-dev

```shell
> canvas-prebuilt@1.6.11 install /Users/tohlaymui/Desktop/performance_analyst_test/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack ZlibError: zlib: Cannot read property 'length' of null
node-pre-gyp ERR! stack     at Unzip.Zlib.(anonymous function) (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/minizlib/index.js:126:21)
node-pre-gyp ERR! stack     at Unzip.write (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/minizlib/index.js:247:21)
node-pre-gyp ERR! stack     at Unzip.flush (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/minizlib/index.js:206:10)
node-pre-gyp ERR! stack     at Unzip.end (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/minizlib/index.js:213:10)
node-pre-gyp ERR! stack     at Unpack.end (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/node-pre-gyp/node_modules/tar/lib/parse.js:416:21)
node-pre-gyp ERR! stack     at Request.onend (internal/streams/legacy.js:44:10)
node-pre-gyp ERR! stack     at emitOne (events.js:130:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:221:7)
node-pre-gyp ERR! stack     at IncomingMessage.<anonymous> (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/request/request.js:1085:12)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:322:30)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/tohlaymui/.nvm/versions/node/v9.1.0/bin/node" "/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/tohlaymui/Desktop/performance_analyst_test/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v9.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
zlib: Cannot read property 'length' of null
npm WARN mocha-react-native@0.6.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN mocha-react-native@0.6.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-create-fragment@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-linked-state-mixin@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-perf@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-pure-render-mixin@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-update@15.1.0 requires a peer of react@^15.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-mock@0.2.7 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-mock@0.2.7 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN webdriverio-test@1.0.0 No repository field.
npm WARN The package wdio-appium-service is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by wswebcreation** [comment]
Hi @LayMuiToh 

Thanks for the issue, I've been testing this with Node 8 and 9 and I don't have an issue with installing the module. I know there is an issue with Node 10 which I'm going to fix soon, but you are on 9

Are you behind a proxy or something?

**Comment by LayMuiToh** [comment]
No, I can install other wdio* modules without any issue but just can't install this modules wdio-native-app-compare. is this any difference from wdio-applitools-service?
I need this to do visual regression testing for mobile native app.
my package.json: 
```
"devDependencies": {
    "@applitools/eyes.webdriverio": "^2.0.0",
    "appium": "^1.10.1",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2015-node": "^6.1.1",
    "babel-preset-react-native": "^4.0.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "eyes.selenium": "^3.6.2",
    "node-wav-player": "^0.1.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-applitools-service": "^0.2.2",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-sync": "^0.7.3",
    "webdriverio": "^4.14.1"
  },
```

**Comment by LayMuiToh** [comment]
@wswebcreation what do I need to do to get this node modules installed?
can have the take at your package.json?

**Comment by wswebcreation** [comment]
First of all this module is free in comparison to applitools. But applitools has a nice dashboard. This module will only tell you if there is a different and save the diff in a folder.

You're the first who has troubles downloading the module. Try to remove all node_modules, remove the package-lock.json and do a new npm install

If that also doesn't work then I don't know what else could be the problem

**Comment by LayMuiToh** [comment]
@wswebcreation , I tried applitools with webdriverio, it didn't work for me neither.
so I am quite keen to try using your node module.
I remove node_modules, run yarn install, npm install, 
node --version
v9.1.0
npm --version
6.7.0

Just curious, can I see the result of your npm install wdio-native-app-compare ?

**Comment by LayMuiToh** [comment]
I managed to install after I upgrade my node
node --version
v10.15.1

+ wdio-native-app-compare@0.7.0
added 37 packages from 22 contributors and audited 11403 packages in 15.882s
found 20 vulnerabilities (5 low, 10 moderate, 5 high)

**Comment by wswebcreation** [comment]
Ahh, cool

Strangely enough it should also work with V8
